apiVersion: v1
kind: Service
metadata:
  name: planty1
  labels:
    app: planty1
spec:
  selector:
    app: planty1
  ports:
  - protocol: "TCP"
    port: 80 # Port on which the service is exposed
    targetPort: 8080 # Port on the pod that the service forwards to
  type: NodePort # Type of service
